### ISSUE TITLE
Allow searching object by ID and name

### ISSUE THREAD

**Issue by dickens88** [center-for-threat-informed-defense/attack-workbench-frontend#312]
Hi, 

I'm using Workbench, I really like this platform and It makes TTP entry easier. 

I met some problem when adding new TTP object with workbench:
1) I would like to allow searching object (techniques, groups, software, etc) by it's ID. As a blue team, when we got a penetration  test report. we need to convert the content of report to TTPs. we may search from google or ATT&CK-website for the technique name and ID, then I turn to workbench and trying to find the particular object and write procedure after it. Currently, the search box seems not supprt searching by ID, and it's also inconvenient to find the object by name. I need to spend a lot of time to search and try different key words.
2) I found there is a similar requirement in the issue list #163 , I think it should also works for me.

Thanks team

**Comment by clemiller** [comment]
Hi @dickens88,

Thank you for opening an issue for this! I'm glad to hear you're enjoying the Workbench application. I agree that being able to search objects by ID would be a very good addition. I will add this issue to our [v1.5.0 milestone](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/milestone/12) for object & table improvements.

**Comment by clemiller** [comment]
Hi @dickens,

We found a bug in the search functionality which is the source of the difficulties with searching by name. The fix for this bug is now staged on `develop`. Additionally, while we were changing some of the search functionality, we went ahead and implemented searching by ATT&CK IDs. You can pull the latest changes on `develop` from the [REST API](https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/tree/develop) for this functionality to take effect.

Closing this issue as it was resolved in [workbench-front-end#303](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/303) and [workbench-rest-api#163](https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/pull/163)
