### ISSUE TITLE
Is there a way to add more options to Platforms?

### ISSUE THREAD

**Issue by ocorir** [center-for-threat-informed-defense/attack-workbench-frontend#336]
When creating a new technique the only options currently for platform are the ones tied to the domains. Is there a way to add a new domain and specify new platforms?

**Comment by clemiller** [comment]
Hi @ocorir,

You can specify other platforms by editing the `x_mitre_platforms` properties in the [allowed values file](https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/blob/master/app/config/allowed-values.json) on the REST API and restarting the server. Since the Enterprise, Mobile, and ICS domains are hard-coded on the front-end, you would need to update the platforms for the existing domains in that file.

As for adding new domains, in future, we are planning to add functionality to [create, edit](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/36), and [view](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/35) domains, where users can specify [domain-specific properties](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/38) such as platforms.

I hope this helps!

**Comment by ocorir** [comment]
Thanks Charissa!

**Comment by darksheer** [comment]
Tried this and it actually doesn't work.  After editing the file, the drop-down GUI interface doesn't display the new domain nor does it allow for election for any of the platforms.

**Comment by clemiller** [comment]
Hi @darksheer,

That's correct - as of now, the Workbench does not support adding new domains, only the platforms for _existing_ domains can be updated by modifying `allowed-values.json`.

**Comment by darksheer** [comment]
Any plans for the future?  Other tooling options that might work in the mean time?  The ATT&CK framework is great, but the lack of supported tooling surely eliminates the incentive to help contribute to the overall projects - either personal or professional -- my .2 cents.
